export const CHANGE_LANGUAGE = 'LANGUAGE/CHANGE_LANGUAGE'
export const ADD_LANGUAGE = 'LANGUAGE/ADD_LANGUAGE'
export const FETCH_RECOMMEND_PRODUCTS_START = 
"RECOMMEND/FETCH_RECOMMEND_PRODUCTS_START"; 
export const FETCH_RECOMMEND_PRODUCTS_SUCCESS = 
"RECOMMEND/FETCH_RECOMMEND_PRODUCTS_SUCCESS"; 
export const FETCH_RECOMMEND_PRODUCTS_FAIL = 
"RECOMMEND/FETCH_RECOMMEND_PRODUCTS_FAIL"; 